version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=dynamodb,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./local/localstack}:/var/lib/localstack"
      - "${LOCALSTACK_VOLUME_DIR:-./local/localstack/init}:/etc/localstack/init"

  dynamodb-admin:
    depends_on: [localstack]
    container_name: "dynamodb-admin"
    build:
      dockerfile: ./local/dynamodb-admin/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566

  cognito-local:
    depends_on: [localstack]
    container_name: "cognito-local"
    image: jagregory/cognito-local
    ports:
      - "9229:9229"
